name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Package application
      run: zip -r app.zip .

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.AWS_EC2_HOST }}
        USERNAME: ${{ secrets.AWS_EC2_USER }}
        PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
      run: |
        APP_PATH="/home/ec2-user/Program/VD"

        echo "Connecting to EC2 instance..."
        scp -o "StrictHostKeyChecking=no" -i "$PRIVATE_KEY" app.zip $USERNAME@$HOST:$APP_PATH/app.zip

        ssh -o "StrictHostKeyChecking=no" -i "$PRIVATE_KEY" $USERNAME@$HOST << EOF
          source ~/miniconda3/etc/profile.d/conda.sh
          conda activate vd
          mkdir -p $APP_PATH
          cd $APP_PATH
          unzip -o app.zip
          nohup streamlit run your_script_name.py --server.port 8501 & 
        EOF
